apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: eventinghello
spec:
  template:
    metadata:
      name: eventinghello-v1
      annotations:
        autoscaling.knative.dev/target: "1"
    spec:
      containers:
        - image: bilal/demo:latest
          name: user-container
          livenessProbe:
            httpGet:
              path: /health  # Change this path to your service's health endpoint
              port: 8080     # Adjust this port as needed
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health  # You can use the same path or a different one
              port: 8080     # Ensure this port matches your application
            initialDelaySeconds: 5
            periodSeconds: 10